### ISSUE TITLE
Use vis's `tabwidth` and `expandtab` values

### ISSUE THREAD

**Issue by ingolemo** [ingolemo/vis-smart-backspace#1]
This plugin should respect the values set by vis, but this would require vis to expose these values in the lua api.

**Comment by milhnl** [comment]
Hi! I made something which allows you to use this with older versions of vis. It'll probably take a while before 0.9 lands in some stable repositories. Might be useful to you or other users of your plugin :)

[vis-options-backport](https://github.com/milhnl/vis-options-backport)
